# Generated by Django 3.1.3 on 2020-11-18 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_operatormore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
