# Generated by Django 3.1.3 on 2020-12-07 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatormore',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='core.client'),
        ),
    ]
