# Generated by Django 3.1.3 on 2020-12-07 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201207_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatormore',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operator', to='core.client'),
        ),
        migrations.AlterField(
            model_name='operatormore',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
