# Generated by Django 3.1.3 on 2021-01-20 23:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscription',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('EAUBELIX', 'Eau-Belix'), ('FORMATION', 'Formation')], default=list, max_length=255, null=True, verbose_name='Subscriptions'), null=True, size=None),
        ),
    ]
