# Generated by Django 3.1.3 on 2021-03-15 01:05

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210120_2334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subscription',
        ),
        migrations.CreateModel(
            name='ClientMore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('EAUBELIX', 'Eau-Belix'), ('FORMATION', 'Formation'), ('NONE', 'Aucune')], default='NONE', max_length=255, null=True, verbose_name='Subscriptions'), null=True, size=None)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
