# Generated by Django 3.1.3 on 2021-03-15 01:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210315_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmore',
            name='subscription',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('EAUBELIX', 'Eau-Belix'), ('FORMATION', 'Formation')], default=None, max_length=255, null=True, verbose_name='Subscriptions'), null=True, size=None),
        ),
    ]
