# Generated by Django 3.1.3 on 2020-12-07 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_auto_20201207_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boiler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('control_chart', models.ImageField(upload_to='')),
                ('flow_chart', models.ImageField(upload_to='')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.client')),
            ],
        ),
        migrations.CreateModel(
            name='BoilerMinMax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inhihitor_min', models.IntegerField()),
                ('inhihitor_max', models.IntegerField()),
                ('p_min', models.IntegerField()),
                ('p_max', models.IntegerField()),
                ('m_min', models.IntegerField()),
                ('m_max', models.IntegerField()),
                ('oh_min', models.IntegerField()),
                ('oh_max', models.IntegerField()),
                ('cl_min', models.IntegerField()),
                ('cl_max', models.IntegerField()),
                ('so3_min', models.IntegerField()),
                ('so3_max', models.IntegerField()),
                ('cond_min', models.IntegerField()),
                ('cond_max', models.IntegerField()),
                ('pointeaux_min', models.FloatField()),
                ('pointeaux_max', models.FloatField()),
                ('mbd_min', models.IntegerField()),
                ('mbd_max', models.IntegerField()),
                ('on_off_min', models.BooleanField(default=True)),
                ('on_off_max', models.BooleanField(default=False)),
                ('vapor_pound_kg_min', models.IntegerField()),
                ('vapor_pound_kg_max', models.IntegerField()),
                ('vaper_cond_min', models.IntegerField()),
                ('vaper_cond_max', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ClosedNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ClosedNetworkData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Pretreatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PretreatmentData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='WaterTower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='WaterTowerData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='BoilerData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('inhihitor', models.IntegerField()),
                ('p', models.IntegerField()),
                ('m', models.IntegerField()),
                ('oh', models.IntegerField()),
                ('cl', models.IntegerField()),
                ('so3', models.IntegerField()),
                ('cond', models.IntegerField()),
                ('pointeaux', models.FloatField()),
                ('mbd', models.IntegerField()),
                ('on_off', models.BooleanField()),
                ('vapor_pound_kg', models.IntegerField()),
                ('vaper_cond', models.IntegerField()),
                ('boiler', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eauxbelix.boiler')),
            ],
        ),
        migrations.AddField(
            model_name='boiler',
            name='min_max',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eauxbelix.boilerminmax'),
        ),
    ]
