# Generated by Django 3.1.3 on 2020-12-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eauxbelix', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boiler',
            name='control_chart',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='boiler',
            name='flow_chart',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
