# Generated by Django 3.1.3 on 2020-12-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eauxbelix', '0002_auto_20201207_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boiler',
            name='control_chart',
            field=models.ImageField(blank=True, default=0, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='boiler',
            name='flow_chart',
            field=models.ImageField(blank=True, default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
