# Generated by Django 3.1.3 on 2020-12-07 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eauxbelix', '0003_auto_20201207_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boilerdata',
            name='boiler',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boiler_data', to='eauxbelix.boiler'),
        ),
    ]
