# Generated by Django 3.1.3 on 2020-12-07 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eauxbelix', '0005_auto_20201207_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boiler',
            name='min_max',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eauxbelix.boilerminmax'),
        ),
    ]
