# Generated by Django 3.1.3 on 2021-03-13 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eauxbelix', '0006_auto_20201207_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boilerdata',
            name='cl',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boilerdata',
            name='cond',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boilerdata',
            name='inhihitor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boilerdata',
            name='m',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boilerdata',
            name='mbd',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boilerdata',
            name='oh',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boilerdata',
            name='on_off',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boilerdata',
            name='p',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boilerdata',
            name='pointeaux',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boilerdata',
            name='so3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boilerdata',
            name='vaper_cond',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boilerdata',
            name='vapor_pound_kg',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
