# Generated by Django 3.1.3 on 2021-03-15 05:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eauxbelix', '0008_auto_20210315_0246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boilerdata',
            old_name='inhihitor',
            new_name='inhibitor',
        ),
        migrations.RenameField(
            model_name='boilerminmax',
            old_name='inhihitor_max',
            new_name='inhibitor_max',
        ),
        migrations.RenameField(
            model_name='boilerminmax',
            old_name='inhihitor_min',
            new_name='inhibitor_min',
        ),
        migrations.AlterField(
            model_name='boiler',
            name='boiler_data_shown',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('inhibitor', 'Inhibiteur'), ('p', 'P'), ('m', 'M'), ('oh', 'OH'), ('cl', 'Cl-'), ('so3', 'SO3'), ('cond', 'Cond'), ('pointeaux', 'Pointeaux'), ('mbd', 'MBD(s)'), ('on_off', 'On / Off'), ('vapor_pound_kg', 'Vapeur(lbs / kg)'), ('vaper_cond', 'Vapeur(Cond)')], default=None, max_length=255, null=True, verbose_name='Boiler Data Shown'), size=None),
        ),
    ]
