# Generated by Django 3.1.3 on 2021-04-09 15:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eauxbelix', '0011_auto_20210409_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watertower',
            name='water_tower_data_shown',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Dipslide', 'Dipslide'), ('inhibitor', 'Inhibiteur'), ('cond', 'Cond'), ('orp', 'ORP'), ('cl2_libre', 'CL2 Libre'), ('atp_l', 'ATP L'), ('atp_t', 'ATP T'), ('atp', 'ATP'), ('iron', 'Fer'), ('copper', 'Cuivre'), ('p', 'P'), ('m', 'M'), ('cl', 'Cl-'), ('appoint', 'Appoint'), ('purge', 'Purge'), ('cycle', 'Cycle'), ('dt', 'DT'), ('ca', 'Ca'), ('ph', 'pH'), ('bw', 'BW'), ('p1', 'P1'), ('p2', 'P2'), ('p3', 'P3'), ('p4', 'P4')], default=None, max_length=255, null=True, verbose_name='Water Tower Data Shown'), size=None),
        ),
    ]
