# Generated by Django 3.1.3 on 2021-04-09 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210315_0207'),
        ('eauxbelix', '0014_auto_20210409_1943'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name': 'Inventories', 'verbose_name_plural': 'Inventory'},
        ),
        migrations.AlterModelOptions(
            name='pretreatment',
            options={'verbose_name': 'Pretreatments', 'verbose_name_plural': 'Pretreatment'},
        ),
        migrations.AddField(
            model_name='inventory',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pretreatment',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pretreatment',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
