# Generated by Django 3.1.3 on 2021-04-09 23:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eauxbelix', '0015_auto_20210409_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('fonction', models.CharField(max_length=100)),
                ('format', models.CharField(max_length=100)),
                ('min', models.IntegerField(blank=True, null=True)),
                ('max', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Products',
                'verbose_name_plural': 'Product',
            },
        ),
        migrations.AlterModelOptions(
            name='inventorydata',
            options={'verbose_name': 'Inventory Data', 'verbose_name_plural': 'Inventory Data'},
        ),
        migrations.AddField(
            model_name='inventorydata',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventorydata',
            name='inventory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eauxbelix.inventory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventorydata',
            name='operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventorydata',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventorydata',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eauxbelix.product'),
            preserve_default=False,
        ),
    ]
