# Generated by Django 3.1.3 on 2021-04-12 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210315_0207'),
        ('eauxbelix', '0016_auto_20210409_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='client',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.client'),
        ),
    ]
