# Generated by Django 3.1.3 on 2021-05-24 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210315_0207'),
        ('eauxbelix', '0018_auto_20210524_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pretreatment',
            name='client',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.client'),
        ),
    ]
