# Generated by Django 3.1.3 on 2021-03-15 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0004_auto_20210312_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='section',
            field=models.CharField(choices=[('ANALYSIS', 'Analyses'), ('PRETREATMENT', 'Prétraitement'), ('CHEMICAL_TREATMENT', 'Traitement Chimique'), ('CONTROL', 'Controle'), ('WATER_TOWER', "Tours d'eau"), ('BOILER', 'Chaudière'), ('MICROBIOLOGY', 'Microbiologie'), ('CLOSED_NETWORK', 'Réseaux fermés')], default='ANALYSIS', max_length=255, null=True, verbose_name='Section'),
        ),
    ]
